package com.app.model;
// Generated May 16, 2016 4:54:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cenovnik generated by hbm2java
 */
@Entity
@Table(name = "cenovnik", catalog = "pinf2016")
public class Cenovnik implements java.io.Serializable {

	private Long idCenovnika;
	private Preduzece preduzece;
	private String nazivCenovnika;
	private Date datumPrimene;
	private Set<StavkeCenovnika> stavkeCenovnikas = new HashSet<StavkeCenovnika>(0);

	public Cenovnik() {
	}

	public Cenovnik(Preduzece preduzece, Date datumPrimene) {
		this.preduzece = preduzece;
		this.datumPrimene = datumPrimene;
	}

	public Cenovnik(Preduzece preduzece, String nazivCenovnika, Date datumPrimene,
			Set<StavkeCenovnika> stavkeCenovnikas) {
		this.preduzece = preduzece;
		this.nazivCenovnika = nazivCenovnika;
		this.datumPrimene = datumPrimene;
		this.stavkeCenovnikas = stavkeCenovnikas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CENOVNIKA", unique = true, nullable = false)
	public Long getIdCenovnika() {
		return this.idCenovnika;
	}

	public void setIdCenovnika(Long idCenovnika) {
		this.idCenovnika = idCenovnika;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PREDUZECA", nullable = false)
	public Preduzece getPreduzece() {
		return this.preduzece;
	}

	public void setPreduzece(Preduzece preduzece) {
		this.preduzece = preduzece;
	}

	@Column(name = "NAZIV_CENOVNIKA", length = 30)
	public String getNazivCenovnika() {
		return this.nazivCenovnika;
	}

	public void setNazivCenovnika(String nazivCenovnika) {
		this.nazivCenovnika = nazivCenovnika;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATUM_PRIMENE", nullable = false, length = 10)
	public Date getDatumPrimene() {
		return this.datumPrimene;
	}

	public void setDatumPrimene(Date datumPrimene) {
		this.datumPrimene = datumPrimene;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cenovnik")
	public Set<StavkeCenovnika> getStavkeCenovnikas() {
		return this.stavkeCenovnikas;
	}

	public void setStavkeCenovnikas(Set<StavkeCenovnika> stavkeCenovnikas) {
		this.stavkeCenovnikas = stavkeCenovnikas;
	}

}
