package com.app.model;
// Generated Jun 20, 2016 4:41:29 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GrupaProizvoda generated by hbm2java
 */
@Entity
@Table(name = "grupa_proizvoda", catalog = "pinf2016")
public class GrupaProizvoda implements java.io.Serializable {

	private Long idGrupe;
	private Porez porez;
	private Preduzece preduzece;
	private String sifraGrupe;
	private String nazivGrupe;
	private Set<KatalogRobeIUsluga> katalogRobeIUslugas = new HashSet<KatalogRobeIUsluga>(0);

	public GrupaProizvoda() {
	}

	public GrupaProizvoda(Porez porez, Preduzece preduzece, String sifraGrupe, String nazivGrupe) {
		this.porez = porez;
		this.preduzece = preduzece;
		this.sifraGrupe = sifraGrupe;
		this.nazivGrupe = nazivGrupe;
	}

	public GrupaProizvoda(Porez porez, Preduzece preduzece, String sifraGrupe, String nazivGrupe,
			Set<KatalogRobeIUsluga> katalogRobeIUslugas) {
		this.porez = porez;
		this.preduzece = preduzece;
		this.sifraGrupe = sifraGrupe;
		this.nazivGrupe = nazivGrupe;
		this.katalogRobeIUslugas = katalogRobeIUslugas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_GRUPE", unique = true, nullable = false)
	public Long getIdGrupe() {
		return this.idGrupe;
	}

	public void setIdGrupe(Long idGrupe) {
		this.idGrupe = idGrupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POREZA", nullable = false)
	public Porez getPorez() {
		return this.porez;
	}

	public void setPorez(Porez porez) {
		this.porez = porez;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PREDUZECA", nullable = false)
	public Preduzece getPreduzece() {
		return this.preduzece;
	}

	public void setPreduzece(Preduzece preduzece) {
		this.preduzece = preduzece;
	}

	@Column(name = "SIFRA_GRUPE", nullable = false, length = 4)
	public String getSifraGrupe() {
		return this.sifraGrupe;
	}

	public void setSifraGrupe(String sifraGrupe) {
		this.sifraGrupe = sifraGrupe;
	}

	@Column(name = "NAZIV_GRUPE", nullable = false, length = 100)
	public String getNazivGrupe() {
		return this.nazivGrupe;
	}

	public void setNazivGrupe(String nazivGrupe) {
		this.nazivGrupe = nazivGrupe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupaProizvoda")
	public Set<KatalogRobeIUsluga> getKatalogRobeIUslugas() {
		return this.katalogRobeIUslugas;
	}

	public void setKatalogRobeIUslugas(Set<KatalogRobeIUsluga> katalogRobeIUslugas) {
		this.katalogRobeIUslugas = katalogRobeIUslugas;
	}

}
