package com.app.model;
// Generated Jun 20, 2016 4:41:29 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KatalogRobeIUsluga generated by hbm2java
 */
@Entity
@Table(name = "katalog_robe_i_usluga", catalog = "pinf2016")
public class KatalogRobeIUsluga implements java.io.Serializable {

	private Long idArtikla;
	private GrupaProizvoda grupaProizvoda;
	private JediniceMere jediniceMere;
	private String sifraArtikla;
	private String nazivArtikla;
	private Set<StavkeFaktureOtpremnice> stavkeFaktureOtpremnices = new HashSet<StavkeFaktureOtpremnice>(0);
	private Set<StavkeCenovnika> stavkeCenovnikas = new HashSet<StavkeCenovnika>(0);
	private Set<StavkeNarudzbe> stavkeNarudzbes = new HashSet<StavkeNarudzbe>(0);

	public KatalogRobeIUsluga() {
	}

	public KatalogRobeIUsluga(GrupaProizvoda grupaProizvoda, JediniceMere jediniceMere, String sifraArtikla,
			String nazivArtikla) {
		this.grupaProizvoda = grupaProizvoda;
		this.jediniceMere = jediniceMere;
		this.sifraArtikla = sifraArtikla;
		this.nazivArtikla = nazivArtikla;
	}

	public KatalogRobeIUsluga(GrupaProizvoda grupaProizvoda, JediniceMere jediniceMere, String sifraArtikla,
			String nazivArtikla, Set<StavkeFaktureOtpremnice> stavkeFaktureOtpremnices,
			Set<StavkeCenovnika> stavkeCenovnikas, Set<StavkeNarudzbe> stavkeNarudzbes) {
		this.grupaProizvoda = grupaProizvoda;
		this.jediniceMere = jediniceMere;
		this.sifraArtikla = sifraArtikla;
		this.nazivArtikla = nazivArtikla;
		this.stavkeFaktureOtpremnices = stavkeFaktureOtpremnices;
		this.stavkeCenovnikas = stavkeCenovnikas;
		this.stavkeNarudzbes = stavkeNarudzbes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ARTIKLA", unique = true, nullable = false)
	public Long getIdArtikla() {
		return this.idArtikla;
	}

	public void setIdArtikla(Long idArtikla) {
		this.idArtikla = idArtikla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GRUPE", nullable = false)
	public GrupaProizvoda getGrupaProizvoda() {
		return this.grupaProizvoda;
	}

	public void setGrupaProizvoda(GrupaProizvoda grupaProizvoda) {
		this.grupaProizvoda = grupaProizvoda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JEDINICE_MERE", nullable = false)
	public JediniceMere getJediniceMere() {
		return this.jediniceMere;
	}

	public void setJediniceMere(JediniceMere jediniceMere) {
		this.jediniceMere = jediniceMere;
	}

	@Column(name = "SIFRA_ARTIKLA", nullable = false, length = 20)
	public String getSifraArtikla() {
		return this.sifraArtikla;
	}

	public void setSifraArtikla(String sifraArtikla) {
		this.sifraArtikla = sifraArtikla;
	}

	@Column(name = "NAZIV_ARTIKLA", nullable = false, length = 100)
	public String getNazivArtikla() {
		return this.nazivArtikla;
	}

	public void setNazivArtikla(String nazivArtikla) {
		this.nazivArtikla = nazivArtikla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "katalogRobeIUsluga")
	public Set<StavkeFaktureOtpremnice> getStavkeFaktureOtpremnices() {
		return this.stavkeFaktureOtpremnices;
	}

	public void setStavkeFaktureOtpremnices(Set<StavkeFaktureOtpremnice> stavkeFaktureOtpremnices) {
		this.stavkeFaktureOtpremnices = stavkeFaktureOtpremnices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "katalogRobeIUsluga")
	public Set<StavkeCenovnika> getStavkeCenovnikas() {
		return this.stavkeCenovnikas;
	}

	public void setStavkeCenovnikas(Set<StavkeCenovnika> stavkeCenovnikas) {
		this.stavkeCenovnikas = stavkeCenovnikas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "katalogRobeIUsluga")
	public Set<StavkeNarudzbe> getStavkeNarudzbes() {
		return this.stavkeNarudzbes;
	}

	public void setStavkeNarudzbes(Set<StavkeNarudzbe> stavkeNarudzbes) {
		this.stavkeNarudzbes = stavkeNarudzbes;
	}

}
