package com.app.model;
// Generated Jun 20, 2016 4:41:29 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Narudzba generated by hbm2java
 */
@Entity
@Table(name = "narudzba", catalog = "pinf2016")
public class Narudzba implements java.io.Serializable {

	private Long idNarudzbe;
	private PoslovnaGodina poslovnaGodina;
	private PoslovniPartner poslovniPartner;
	private int brojNarudzbe;
	private Date datumNarucivanja;
	private Date rokIsporuke;
	private String nacinOtpreme;
	private String nacinPlacanja;
	private char statusNarudzbe;
	private Set<FakturaOtpremnica> fakturaOtpremnicas = new HashSet<FakturaOtpremnica>(0);
	private Set<StavkeNarudzbe> stavkeNarudzbes = new HashSet<StavkeNarudzbe>(0);

	public Narudzba() {
	}

	public Narudzba(PoslovnaGodina poslovnaGodina, int brojNarudzbe, Date datumNarucivanja, Date rokIsporuke,
			char statusNarudzbe) {
		this.poslovnaGodina = poslovnaGodina;
		this.brojNarudzbe = brojNarudzbe;
		this.datumNarucivanja = datumNarucivanja;
		this.rokIsporuke = rokIsporuke;
		this.statusNarudzbe = statusNarudzbe;
	}

	public Narudzba(PoslovnaGodina poslovnaGodina, PoslovniPartner poslovniPartner, int brojNarudzbe,
			Date datumNarucivanja, Date rokIsporuke, String nacinOtpreme, String nacinPlacanja, char statusNarudzbe,
			Set<FakturaOtpremnica> fakturaOtpremnicas, Set<StavkeNarudzbe> stavkeNarudzbes) {
		this.poslovnaGodina = poslovnaGodina;
		this.poslovniPartner = poslovniPartner;
		this.brojNarudzbe = brojNarudzbe;
		this.datumNarucivanja = datumNarucivanja;
		this.rokIsporuke = rokIsporuke;
		this.nacinOtpreme = nacinOtpreme;
		this.nacinPlacanja = nacinPlacanja;
		this.statusNarudzbe = statusNarudzbe;
		this.fakturaOtpremnicas = fakturaOtpremnicas;
		this.stavkeNarudzbes = stavkeNarudzbes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_NARUDZBE", unique = true, nullable = false)
	public Long getIdNarudzbe() {
		return this.idNarudzbe;
	}

	public void setIdNarudzbe(Long idNarudzbe) {
		this.idNarudzbe = idNarudzbe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POSLOVNE_GODINE", nullable = false)
	public PoslovnaGodina getPoslovnaGodina() {
		return this.poslovnaGodina;
	}

	public void setPoslovnaGodina(PoslovnaGodina poslovnaGodina) {
		this.poslovnaGodina = poslovnaGodina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARTNERSTVA")
	public PoslovniPartner getPoslovniPartner() {
		return this.poslovniPartner;
	}

	public void setPoslovniPartner(PoslovniPartner poslovniPartner) {
		this.poslovniPartner = poslovniPartner;
	}

	@Column(name = "BROJ_NARUDZBE", nullable = false, precision = 6, scale = 0)
	public int getBrojNarudzbe() {
		return this.brojNarudzbe;
	}

	public void setBrojNarudzbe(int brojNarudzbe) {
		this.brojNarudzbe = brojNarudzbe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATUM_NARUCIVANJA", nullable = false, length = 10)
	public Date getDatumNarucivanja() {
		return this.datumNarucivanja;
	}

	public void setDatumNarucivanja(Date datumNarucivanja) {
		this.datumNarucivanja = datumNarucivanja;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ROK_ISPORUKE", nullable = false, length = 10)
	public Date getRokIsporuke() {
		return this.rokIsporuke;
	}

	public void setRokIsporuke(Date rokIsporuke) {
		this.rokIsporuke = rokIsporuke;
	}

	@Column(name = "NACIN_OTPREME", length = 30)
	public String getNacinOtpreme() {
		return this.nacinOtpreme;
	}

	public void setNacinOtpreme(String nacinOtpreme) {
		this.nacinOtpreme = nacinOtpreme;
	}

	@Column(name = "NACIN_PLACANJA", length = 30)
	public String getNacinPlacanja() {
		return this.nacinPlacanja;
	}

	public void setNacinPlacanja(String nacinPlacanja) {
		this.nacinPlacanja = nacinPlacanja;
	}

	@Column(name = "STATUS_NARUDZBE", nullable = false, length = 1)
	public char getStatusNarudzbe() {
		return this.statusNarudzbe;
	}

	public void setStatusNarudzbe(char statusNarudzbe) {
		this.statusNarudzbe = statusNarudzbe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "narudzba")
	public Set<FakturaOtpremnica> getFakturaOtpremnicas() {
		return this.fakturaOtpremnicas;
	}

	public void setFakturaOtpremnicas(Set<FakturaOtpremnica> fakturaOtpremnicas) {
		this.fakturaOtpremnicas = fakturaOtpremnicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "narudzba")
	public Set<StavkeNarudzbe> getStavkeNarudzbes() {
		return this.stavkeNarudzbes;
	}

	public void setStavkeNarudzbes(Set<StavkeNarudzbe> stavkeNarudzbes) {
		this.stavkeNarudzbes = stavkeNarudzbes;
	}

}
