package com.app.model;
// Generated Jun 20, 2016 4:41:29 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Porez generated by hbm2java
 */
@Entity
@Table(name = "porez", catalog = "pinf2016")
public class Porez implements java.io.Serializable {

	private Long idPoreza;
	private String porNaziv;
	private boolean posVazi;
	private Set<PoreskaStopa> poreskaStopas = new HashSet<PoreskaStopa>(0);
	private Set<GrupaProizvoda> grupaProizvodas = new HashSet<GrupaProizvoda>(0);

	public Porez() {
	}

	public Porez(String porNaziv, boolean posVazi) {
		this.porNaziv = porNaziv;
		this.posVazi = posVazi;
	}

	public Porez(String porNaziv, boolean posVazi, Set<PoreskaStopa> poreskaStopas,
			Set<GrupaProizvoda> grupaProizvodas) {
		this.porNaziv = porNaziv;
		this.posVazi = posVazi;
		this.poreskaStopas = poreskaStopas;
		this.grupaProizvodas = grupaProizvodas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_POREZA", unique = true, nullable = false)
	public Long getIdPoreza() {
		return this.idPoreza;
	}

	public void setIdPoreza(Long idPoreza) {
		this.idPoreza = idPoreza;
	}

	@Column(name = "POR_NAZIV", nullable = false, length = 120)
	public String getPorNaziv() {
		return this.porNaziv;
	}

	public void setPorNaziv(String porNaziv) {
		this.porNaziv = porNaziv;
	}

	@Column(name = "POS_VAZI", nullable = false)
	public boolean isPosVazi() {
		return this.posVazi;
	}

	public void setPosVazi(boolean posVazi) {
		this.posVazi = posVazi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "porez")
	public Set<PoreskaStopa> getPoreskaStopas() {
		return this.poreskaStopas;
	}

	public void setPoreskaStopas(Set<PoreskaStopa> poreskaStopas) {
		this.poreskaStopas = poreskaStopas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "porez")
	public Set<GrupaProizvoda> getGrupaProizvodas() {
		return this.grupaProizvodas;
	}

	public void setGrupaProizvodas(Set<GrupaProizvoda> grupaProizvodas) {
		this.grupaProizvodas = grupaProizvodas;
	}

}
