package com.app.model;
// Generated May 16, 2016 4:54:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoreskaStopa generated by hbm2java
 */
@Entity
@Table(name = "poreska_stopa", catalog = "pinf2016")
public class PoreskaStopa implements java.io.Serializable {

	private Long idStope;
	private Porez porez;
	private BigDecimal iznosStope;
	private Date datumVazenja;

	public PoreskaStopa() {
	}

	public PoreskaStopa(Porez porez, BigDecimal iznosStope, Date datumVazenja) {
		this.porez = porez;
		this.iznosStope = iznosStope;
		this.datumVazenja = datumVazenja;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_STOPE", unique = true, nullable = false)
	public Long getIdStope() {
		return this.idStope;
	}

	public void setIdStope(Long idStope) {
		this.idStope = idStope;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POREZA", nullable = false)
	public Porez getPorez() {
		return this.porez;
	}

	public void setPorez(Porez porez) {
		this.porez = porez;
	}

	@Column(name = "IZNOS_STOPE", nullable = false, precision = 5)
	public BigDecimal getIznosStope() {
		return this.iznosStope;
	}

	public void setIznosStope(BigDecimal iznosStope) {
		this.iznosStope = iznosStope;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATUM_VAZENJA", nullable = false, length = 10)
	public Date getDatumVazenja() {
		return this.datumVazenja;
	}

	public void setDatumVazenja(Date datumVazenja) {
		this.datumVazenja = datumVazenja;
	}

}
