package com.app.model;
// Generated May 16, 2016 4:54:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PoslovnaGodina generated by hbm2java
 */
@Entity
@Table(name = "poslovna_godina", catalog = "pinf2016")
public class PoslovnaGodina implements java.io.Serializable {

	private Long idPoslovneGodine;
	private Preduzece preduzece;
	private short pgGodina2;
	private boolean pgVazi2;
	private Set<Narudzba> narudzbas = new HashSet<Narudzba>(0);
	private Set<FakturaOtpremnica> fakturaOtpremnicas = new HashSet<FakturaOtpremnica>(0);

	public PoslovnaGodina() {
	}

	public PoslovnaGodina(Preduzece preduzece, short pgGodina2, boolean pgVazi2) {
		this.preduzece = preduzece;
		this.pgGodina2 = pgGodina2;
		this.pgVazi2 = pgVazi2;
	}

	public PoslovnaGodina(Preduzece preduzece, short pgGodina2, boolean pgVazi2, Set<Narudzba> narudzbas,
			Set<FakturaOtpremnica> fakturaOtpremnicas) {
		this.preduzece = preduzece;
		this.pgGodina2 = pgGodina2;
		this.pgVazi2 = pgVazi2;
		this.narudzbas = narudzbas;
		this.fakturaOtpremnicas = fakturaOtpremnicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_POSLOVNE_GODINE", unique = true, nullable = false)
	public Long getIdPoslovneGodine() {
		return this.idPoslovneGodine;
	}

	public void setIdPoslovneGodine(Long idPoslovneGodine) {
		this.idPoslovneGodine = idPoslovneGodine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PREDUZECA", nullable = false)
	public Preduzece getPreduzece() {
		return this.preduzece;
	}

	public void setPreduzece(Preduzece preduzece) {
		this.preduzece = preduzece;
	}

	@Column(name = "PG_GODINA2", nullable = false, precision = 4, scale = 0)
	public short getPgGodina2() {
		return this.pgGodina2;
	}

	public void setPgGodina2(short pgGodina2) {
		this.pgGodina2 = pgGodina2;
	}

	@Column(name = "PG_VAZI2", nullable = false)
	public boolean isPgVazi2() {
		return this.pgVazi2;
	}

	public void setPgVazi2(boolean pgVazi2) {
		this.pgVazi2 = pgVazi2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poslovnaGodina")
	public Set<Narudzba> getNarudzbas() {
		return this.narudzbas;
	}

	public void setNarudzbas(Set<Narudzba> narudzbas) {
		this.narudzbas = narudzbas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poslovnaGodina")
	public Set<FakturaOtpremnica> getFakturaOtpremnicas() {
		return this.fakturaOtpremnicas;
	}

	public void setFakturaOtpremnicas(Set<FakturaOtpremnica> fakturaOtpremnicas) {
		this.fakturaOtpremnicas = fakturaOtpremnicas;
	}

}
