package com.app.model;
// Generated May 16, 2016 4:54:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Preduzece generated by hbm2java
 */
@Entity
@Table(name = "preduzece", catalog = "pinf2016")
public class Preduzece implements java.io.Serializable {

	private Long idPreduzeca;
	private SifraDelatnosti sifraDelatnosti;
	private String pib;
	private String maticniBroj;
	private String adresa;
	private String brojTelefona;
	private String email;
	private String banka;
	private String tekuciRacun;
	private Set<GrupaProizvoda> grupaProizvodas = new HashSet<GrupaProizvoda>(0);
	private Set<Cenovnik> cenovniks = new HashSet<Cenovnik>(0);
	private Set<PoslovnaGodina> poslovnaGodinas = new HashSet<PoslovnaGodina>(0);
	private Set<PoslovniPartner> poslovniPartnersForIdPreduzeca = new HashSet<PoslovniPartner>(0);
	private Set<PoslovniPartner> poslovniPartnersForIdPartnera = new HashSet<PoslovniPartner>(0);

	public Preduzece() {
	}

	public Preduzece(SifraDelatnosti sifraDelatnosti, String pib, String maticniBroj, String tekuciRacun) {
		this.sifraDelatnosti = sifraDelatnosti;
		this.pib = pib;
		this.maticniBroj = maticniBroj;
		this.tekuciRacun = tekuciRacun;
	}

	public Preduzece(SifraDelatnosti sifraDelatnosti, String pib, String maticniBroj, String adresa,
			String brojTelefona, String email, String banka, String tekuciRacun, Set<GrupaProizvoda> grupaProizvodas,
			Set<Cenovnik> cenovniks, Set<PoslovnaGodina> poslovnaGodinas,
			Set<PoslovniPartner> poslovniPartnersForIdPreduzeca, Set<PoslovniPartner> poslovniPartnersForIdPartnera) {
		this.sifraDelatnosti = sifraDelatnosti;
		this.pib = pib;
		this.maticniBroj = maticniBroj;
		this.adresa = adresa;
		this.brojTelefona = brojTelefona;
		this.email = email;
		this.banka = banka;
		this.tekuciRacun = tekuciRacun;
		this.grupaProizvodas = grupaProizvodas;
		this.cenovniks = cenovniks;
		this.poslovnaGodinas = poslovnaGodinas;
		this.poslovniPartnersForIdPreduzeca = poslovniPartnersForIdPreduzeca;
		this.poslovniPartnersForIdPartnera = poslovniPartnersForIdPartnera;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PREDUZECA", unique = true, nullable = false)
	public Long getIdPreduzeca() {
		return this.idPreduzeca;
	}

	public void setIdPreduzeca(Long idPreduzeca) {
		this.idPreduzeca = idPreduzeca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SIFRE_DELATNOSTI", nullable = false)
	public SifraDelatnosti getSifraDelatnosti() {
		return this.sifraDelatnosti;
	}

	public void setSifraDelatnosti(SifraDelatnosti sifraDelatnosti) {
		this.sifraDelatnosti = sifraDelatnosti;
	}

	@Column(name = "PIB", nullable = false, length = 9)
	public String getPib() {
		return this.pib;
	}

	public void setPib(String pib) {
		this.pib = pib;
	}

	@Column(name = "MATICNI_BROJ", nullable = false, length = 8)
	public String getMaticniBroj() {
		return this.maticniBroj;
	}

	public void setMaticniBroj(String maticniBroj) {
		this.maticniBroj = maticniBroj;
	}

	@Column(name = "ADRESA", length = 20)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "BROJ_TELEFONA", length = 12)
	public String getBrojTelefona() {
		return this.brojTelefona;
	}

	public void setBrojTelefona(String brojTelefona) {
		this.brojTelefona = brojTelefona;
	}

	@Column(name = "EMAIL", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "BANKA", length = 20)
	public String getBanka() {
		return this.banka;
	}

	public void setBanka(String banka) {
		this.banka = banka;
	}

	@Column(name = "TEKUCI_RACUN", nullable = false, length = 25)
	public String getTekuciRacun() {
		return this.tekuciRacun;
	}

	public void setTekuciRacun(String tekuciRacun) {
		this.tekuciRacun = tekuciRacun;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzece")
	public Set<GrupaProizvoda> getGrupaProizvodas() {
		return this.grupaProizvodas;
	}

	public void setGrupaProizvodas(Set<GrupaProizvoda> grupaProizvodas) {
		this.grupaProizvodas = grupaProizvodas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzece")
	public Set<Cenovnik> getCenovniks() {
		return this.cenovniks;
	}

	public void setCenovniks(Set<Cenovnik> cenovniks) {
		this.cenovniks = cenovniks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzece")
	public Set<PoslovnaGodina> getPoslovnaGodinas() {
		return this.poslovnaGodinas;
	}

	public void setPoslovnaGodinas(Set<PoslovnaGodina> poslovnaGodinas) {
		this.poslovnaGodinas = poslovnaGodinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzeceByIdPreduzeca")
	public Set<PoslovniPartner> getPoslovniPartnersForIdPreduzeca() {
		return this.poslovniPartnersForIdPreduzeca;
	}

	public void setPoslovniPartnersForIdPreduzeca(Set<PoslovniPartner> poslovniPartnersForIdPreduzeca) {
		this.poslovniPartnersForIdPreduzeca = poslovniPartnersForIdPreduzeca;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzeceByIdPartnera")
	public Set<PoslovniPartner> getPoslovniPartnersForIdPartnera() {
		return this.poslovniPartnersForIdPartnera;
	}

	public void setPoslovniPartnersForIdPartnera(Set<PoslovniPartner> poslovniPartnersForIdPartnera) {
		this.poslovniPartnersForIdPartnera = poslovniPartnersForIdPartnera;
	}

}
