package com.app.model;
// Generated May 16, 2016 4:54:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SifraDelatnosti generated by hbm2java
 */
@Entity
@Table(name = "sifra_delatnosti", catalog = "pinf2016")
public class SifraDelatnosti implements java.io.Serializable {

	private Long idSifreDelatnosti;
	private String oznakaSifreDelatnosti;
	private String nazivSifreDelatnosti;
	private Set<Preduzece> preduzeces = new HashSet<Preduzece>(0);

	public SifraDelatnosti() {
	}

	public SifraDelatnosti(String oznakaSifreDelatnosti, String nazivSifreDelatnosti) {
		this.oznakaSifreDelatnosti = oznakaSifreDelatnosti;
		this.nazivSifreDelatnosti = nazivSifreDelatnosti;
	}

	public SifraDelatnosti(String oznakaSifreDelatnosti, String nazivSifreDelatnosti, Set<Preduzece> preduzeces) {
		this.oznakaSifreDelatnosti = oznakaSifreDelatnosti;
		this.nazivSifreDelatnosti = nazivSifreDelatnosti;
		this.preduzeces = preduzeces;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_SIFRE_DELATNOSTI", unique = true, nullable = false)
	public Long getIdSifreDelatnosti() {
		return this.idSifreDelatnosti;
	}

	public void setIdSifreDelatnosti(Long idSifreDelatnosti) {
		this.idSifreDelatnosti = idSifreDelatnosti;
	}

	@Column(name = "OZNAKA_SIFRE_DELATNOSTI", nullable = false, length = 4)
	public String getOznakaSifreDelatnosti() {
		return this.oznakaSifreDelatnosti;
	}

	public void setOznakaSifreDelatnosti(String oznakaSifreDelatnosti) {
		this.oznakaSifreDelatnosti = oznakaSifreDelatnosti;
	}

	@Column(name = "NAZIV_SIFRE_DELATNOSTI", nullable = false, length = 30)
	public String getNazivSifreDelatnosti() {
		return this.nazivSifreDelatnosti;
	}

	public void setNazivSifreDelatnosti(String nazivSifreDelatnosti) {
		this.nazivSifreDelatnosti = nazivSifreDelatnosti;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sifraDelatnosti")
	public Set<Preduzece> getPreduzeces() {
		return this.preduzeces;
	}

	public void setPreduzeces(Set<Preduzece> preduzeces) {
		this.preduzeces = preduzeces;
	}

}
