package com.app.model;
// Generated Jun 20, 2016 4:41:29 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StavkeFaktureOtpremnice generated by hbm2java
 */
@Entity
@Table(name = "stavke_fakture_otpremnice", catalog = "pinf2016")
public class StavkeFaktureOtpremnice implements java.io.Serializable {

	private Long idStavkeFakture;
	private FakturaOtpremnica fakturaOtpremnica;
	private KatalogRobeIUsluga katalogRobeIUsluga;
	private BigDecimal kolicina;
	private BigDecimal rabat;
	private BigDecimal osnovicaPdv;
	private BigDecimal jedinicnaCenaStavkeFakture;

	public StavkeFaktureOtpremnice() {
	}

	public StavkeFaktureOtpremnice(FakturaOtpremnica fakturaOtpremnica, KatalogRobeIUsluga katalogRobeIUsluga,
			BigDecimal kolicina, BigDecimal osnovicaPdv, BigDecimal jedinicnaCenaStavkeFakture) {
		this.fakturaOtpremnica = fakturaOtpremnica;
		this.katalogRobeIUsluga = katalogRobeIUsluga;
		this.kolicina = kolicina;
		this.osnovicaPdv = osnovicaPdv;
		this.jedinicnaCenaStavkeFakture = jedinicnaCenaStavkeFakture;
	}

	public StavkeFaktureOtpremnice(FakturaOtpremnica fakturaOtpremnica, KatalogRobeIUsluga katalogRobeIUsluga,
			BigDecimal kolicina, BigDecimal rabat, BigDecimal osnovicaPdv, BigDecimal jedinicnaCenaStavkeFakture) {
		this.fakturaOtpremnica = fakturaOtpremnica;
		this.katalogRobeIUsluga = katalogRobeIUsluga;
		this.kolicina = kolicina;
		this.rabat = rabat;
		this.osnovicaPdv = osnovicaPdv;
		this.jedinicnaCenaStavkeFakture = jedinicnaCenaStavkeFakture;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_STAVKE_FAKTURE", unique = true, nullable = false)
	public Long getIdStavkeFakture() {
		return this.idStavkeFakture;
	}

	public void setIdStavkeFakture(Long idStavkeFakture) {
		this.idStavkeFakture = idStavkeFakture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FAKTURE_OTPREMNICE", nullable = false)
	public FakturaOtpremnica getFakturaOtpremnica() {
		return this.fakturaOtpremnica;
	}

	public void setFakturaOtpremnica(FakturaOtpremnica fakturaOtpremnica) {
		this.fakturaOtpremnica = fakturaOtpremnica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ARTIKLA", nullable = false)
	public KatalogRobeIUsluga getKatalogRobeIUsluga() {
		return this.katalogRobeIUsluga;
	}

	public void setKatalogRobeIUsluga(KatalogRobeIUsluga katalogRobeIUsluga) {
		this.katalogRobeIUsluga = katalogRobeIUsluga;
	}

	@Column(name = "KOLICINA", nullable = false, precision = 15)
	public BigDecimal getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(BigDecimal kolicina) {
		this.kolicina = kolicina;
	}

	@Column(name = "RABAT", precision = 15)
	public BigDecimal getRabat() {
		return this.rabat;
	}

	public void setRabat(BigDecimal rabat) {
		this.rabat = rabat;
	}

	@Column(name = "OSNOVICA_PDV", nullable = false, precision = 15)
	public BigDecimal getOsnovicaPdv() {
		return this.osnovicaPdv;
	}

	public void setOsnovicaPdv(BigDecimal osnovicaPdv) {
		this.osnovicaPdv = osnovicaPdv;
	}

	@Column(name = "JEDINICNA_CENA_STAVKE_FAKTURE", nullable = false, precision = 15)
	public BigDecimal getJedinicnaCenaStavkeFakture() {
		return this.jedinicnaCenaStavkeFakture;
	}

	public void setJedinicnaCenaStavkeFakture(BigDecimal jedinicnaCenaStavkeFakture) {
		this.jedinicnaCenaStavkeFakture = jedinicnaCenaStavkeFakture;
	}

}
