package com.app.model;
// Generated May 16, 2016 4:54:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StavkeCenovnika generated by hbm2java
 */
@Entity
@Table(name = "stavke_cenovnika", catalog = "pinf2016")
public class StavkeCenovnika implements java.io.Serializable {

	private Long idStavkeCenovnika;
	private Cenovnik cenovnik;
	private KatalogRobeIUsluga katalogRobeIUsluga;
	private BigDecimal jedinicnaCenaStavkeCenovnika;

	public StavkeCenovnika() {
	}

	public StavkeCenovnika(Cenovnik cenovnik, KatalogRobeIUsluga katalogRobeIUsluga,
			BigDecimal jedinicnaCenaStavkeCenovnika) {
		this.cenovnik = cenovnik;
		this.katalogRobeIUsluga = katalogRobeIUsluga;
		this.jedinicnaCenaStavkeCenovnika = jedinicnaCenaStavkeCenovnika;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_STAVKE_CENOVNIKA", unique = true, nullable = false)
	public Long getIdStavkeCenovnika() {
		return this.idStavkeCenovnika;
	}

	public void setIdStavkeCenovnika(Long idStavkeCenovnika) {
		this.idStavkeCenovnika = idStavkeCenovnika;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CENOVNIKA", nullable = false)
	public Cenovnik getCenovnik() {
		return this.cenovnik;
	}

	public void setCenovnik(Cenovnik cenovnik) {
		this.cenovnik = cenovnik;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ARTIKLA", nullable = false)
	public KatalogRobeIUsluga getKatalogRobeIUsluga() {
		return this.katalogRobeIUsluga;
	}

	public void setKatalogRobeIUsluga(KatalogRobeIUsluga katalogRobeIUsluga) {
		this.katalogRobeIUsluga = katalogRobeIUsluga;
	}

	@Column(name = "JEDINICNA_CENA_STAVKE_CENOVNIKA", nullable = false, precision = 15)
	public BigDecimal getJedinicnaCenaStavkeCenovnika() {
		return this.jedinicnaCenaStavkeCenovnika;
	}

	public void setJedinicnaCenaStavkeCenovnika(BigDecimal jedinicnaCenaStavkeCenovnika) {
		this.jedinicnaCenaStavkeCenovnika = jedinicnaCenaStavkeCenovnika;
	}

}
