//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 04:04:46 PM CEST 
//


package com.app.model.invoice;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/faktura}StavkaFaktureOtpremnice" maxOccurs="unbounded"/>
 *         &lt;element name="idNarudzbe" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idPoslovneGodine" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="poslovnaGodina" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="idPartnerstva" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.ftn.uns.ac.rs/faktura}faAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stavkaFaktureOtpremnice",
    "idNarudzbe",
    "idPoslovneGodine",
    "poslovnaGodina",
    "idPartnerstva"
})
@XmlRootElement(name = "FakturaOtpremnica")
public class FakturaOtpremnica {

    @XmlElement(name = "StavkaFaktureOtpremnice", required = true)
    protected List<StavkaFaktureOtpremnice> stavkaFaktureOtpremnice;
    protected long idNarudzbe;
    protected long idPoslovneGodine;
    protected short poslovnaGodina;
    protected long idPartnerstva;
    @XmlAttribute(name = "idFaktureOtpremnice")
    protected Long idFaktureOtpremnice;
    @XmlAttribute(name = "faBroj")
    protected Integer faBroj;
    @XmlAttribute(name = "faTip")
    protected String faTip;
    @XmlAttribute(name = "faDatum")
    protected String faDatum;
    @XmlAttribute(name = "faDatumValute")
    protected String faDatumValute;
    @XmlAttribute(name = "faDatumObracuna")
    protected String faDatumObracuna;
    @XmlAttribute(name = "faUkupno")
    protected BigDecimal faUkupno;
    @XmlAttribute(name = "faRabat")
    protected BigDecimal faRabat;
    @XmlAttribute(name = "faPorez")
    protected BigDecimal faPorez;
    @XmlAttribute(name = "faIznos")
    protected BigDecimal faIznos;
    @XmlAttribute(name = "faTekuciracun")
    protected String faTekuciracun;
    @XmlAttribute(name = "faPoziv")
    protected String faPoziv;
    @XmlAttribute(name = "statusFakture")
    protected String statusFakture;
    @XmlAttribute(name = "dodatneNapomene")
    protected String dodatneNapomene;
    @XmlAttribute(name = "adresaIsporuke")
    protected String adresaIsporuke;
    @XmlAttribute(name = "brojKamiona")
    protected String brojKamiona;
    @XmlAttribute(name = "prevoznik")
    protected String prevoznik;
    @XmlAttribute(name = "robuIRacunIzdao")
    protected String robuIRacunIzdao;
    @XmlAttribute(name = "robuIRacunPreuzeo")
    protected String robuIRacunPreuzeo;

    /**
     * Gets the value of the stavkaFaktureOtpremnice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavkaFaktureOtpremnice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavkaFaktureOtpremnice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StavkaFaktureOtpremnice }
     * 
     * 
     */
    public List<StavkaFaktureOtpremnice> getStavkaFaktureOtpremnice() {
        if (stavkaFaktureOtpremnice == null) {
            stavkaFaktureOtpremnice = new ArrayList<StavkaFaktureOtpremnice>();
        }
        return this.stavkaFaktureOtpremnice;
    }

    /**
     * Gets the value of the idNarudzbe property.
     * 
     */
    public long getIdNarudzbe() {
        return idNarudzbe;
    }

    /**
     * Sets the value of the idNarudzbe property.
     * 
     */
    public void setIdNarudzbe(long value) {
        this.idNarudzbe = value;
    }

    /**
     * Gets the value of the idPoslovneGodine property.
     * 
     */
    public long getIdPoslovneGodine() {
        return idPoslovneGodine;
    }

    /**
     * Sets the value of the idPoslovneGodine property.
     * 
     */
    public void setIdPoslovneGodine(long value) {
        this.idPoslovneGodine = value;
    }

    /**
     * Gets the value of the poslovnaGodina property.
     * 
     */
    public short getPoslovnaGodina() {
        return poslovnaGodina;
    }

    /**
     * Sets the value of the poslovnaGodina property.
     * 
     */
    public void setPoslovnaGodina(short value) {
        this.poslovnaGodina = value;
    }

    /**
     * Gets the value of the idPartnerstva property.
     * 
     */
    public long getIdPartnerstva() {
        return idPartnerstva;
    }

    /**
     * Sets the value of the idPartnerstva property.
     * 
     */
    public void setIdPartnerstva(long value) {
        this.idPartnerstva = value;
    }

    /**
     * Gets the value of the idFaktureOtpremnice property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdFaktureOtpremnice() {
        return idFaktureOtpremnice;
    }

    /**
     * Sets the value of the idFaktureOtpremnice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdFaktureOtpremnice(Long value) {
        this.idFaktureOtpremnice = value;
    }

    /**
     * Gets the value of the faBroj property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFaBroj() {
        return faBroj;
    }

    /**
     * Sets the value of the faBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFaBroj(Integer value) {
        this.faBroj = value;
    }

    /**
     * Gets the value of the faTip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaTip() {
        return faTip;
    }

    /**
     * Sets the value of the faTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaTip(String value) {
        this.faTip = value;
    }

    /**
     * Gets the value of the faDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaDatum() {
        return faDatum;
    }

    /**
     * Sets the value of the faDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaDatum(String value) {
        this.faDatum = value;
    }

    /**
     * Gets the value of the faDatumValute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaDatumValute() {
        return faDatumValute;
    }

    /**
     * Sets the value of the faDatumValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaDatumValute(String value) {
        this.faDatumValute = value;
    }

    /**
     * Gets the value of the faDatumObracuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaDatumObracuna() {
        return faDatumObracuna;
    }

    /**
     * Sets the value of the faDatumObracuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaDatumObracuna(String value) {
        this.faDatumObracuna = value;
    }

    /**
     * Gets the value of the faUkupno property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaUkupno() {
        return faUkupno;
    }

    /**
     * Sets the value of the faUkupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFaUkupno(BigDecimal value) {
        this.faUkupno = value;
    }

    /**
     * Gets the value of the faRabat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaRabat() {
        return faRabat;
    }

    /**
     * Sets the value of the faRabat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFaRabat(BigDecimal value) {
        this.faRabat = value;
    }

    /**
     * Gets the value of the faPorez property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaPorez() {
        return faPorez;
    }

    /**
     * Sets the value of the faPorez property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFaPorez(BigDecimal value) {
        this.faPorez = value;
    }

    /**
     * Gets the value of the faIznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaIznos() {
        return faIznos;
    }

    /**
     * Sets the value of the faIznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFaIznos(BigDecimal value) {
        this.faIznos = value;
    }

    /**
     * Gets the value of the faTekuciracun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaTekuciracun() {
        return faTekuciracun;
    }

    /**
     * Sets the value of the faTekuciracun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaTekuciracun(String value) {
        this.faTekuciracun = value;
    }

    /**
     * Gets the value of the faPoziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaPoziv() {
        return faPoziv;
    }

    /**
     * Sets the value of the faPoziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaPoziv(String value) {
        this.faPoziv = value;
    }

    /**
     * Gets the value of the statusFakture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusFakture() {
        return statusFakture;
    }

    /**
     * Sets the value of the statusFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusFakture(String value) {
        this.statusFakture = value;
    }

    /**
     * Gets the value of the dodatneNapomene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDodatneNapomene() {
        return dodatneNapomene;
    }

    /**
     * Sets the value of the dodatneNapomene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDodatneNapomene(String value) {
        this.dodatneNapomene = value;
    }

    /**
     * Gets the value of the adresaIsporuke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresaIsporuke() {
        return adresaIsporuke;
    }

    /**
     * Sets the value of the adresaIsporuke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresaIsporuke(String value) {
        this.adresaIsporuke = value;
    }

    /**
     * Gets the value of the brojKamiona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojKamiona() {
        return brojKamiona;
    }

    /**
     * Sets the value of the brojKamiona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojKamiona(String value) {
        this.brojKamiona = value;
    }

    /**
     * Gets the value of the prevoznik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevoznik() {
        return prevoznik;
    }

    /**
     * Sets the value of the prevoznik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevoznik(String value) {
        this.prevoznik = value;
    }

    /**
     * Gets the value of the robuIRacunIzdao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRobuIRacunIzdao() {
        return robuIRacunIzdao;
    }

    /**
     * Sets the value of the robuIRacunIzdao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRobuIRacunIzdao(String value) {
        this.robuIRacunIzdao = value;
    }

    /**
     * Gets the value of the robuIRacunPreuzeo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRobuIRacunPreuzeo() {
        return robuIRacunPreuzeo;
    }

    /**
     * Sets the value of the robuIRacunPreuzeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRobuIRacunPreuzeo(String value) {
        this.robuIRacunPreuzeo = value;
    }

}
