//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 06:33:45 PM CEST 
//


package com.app.model.invoice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FakturaRacunIRobuIzdao_QNAME = new QName("", "Racun_i_robu_izdao");
    private final static QName _FakturaRacunIRobuPrimio_QNAME = new QName("", "Racun_i_robu_primio");
    private final static QName _FakturaDodatneNapomene_QNAME = new QName("", "Dodatne_napomene");
    private final static QName _FakturaPodaciOPrevozniku_QNAME = new QName("", "Podaci_o_prevozniku");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faktura }
     * 
     */
    public Faktura createFaktura() {
        return new Faktura();
    }

    /**
     * Create an instance of {@link TPreduzece }
     * 
     */
    public TPreduzece createTPreduzece() {
        return new TPreduzece();
    }

    /**
     * Create an instance of {@link TStavkaFakture }
     * 
     */
    public TStavkaFakture createTStavkaFakture() {
        return new TStavkaFakture();
    }

    /**
     * Create an instance of {@link TPrevoznik }
     * 
     */
    public TPrevoznik createTPrevoznik() {
        return new TPrevoznik();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Racun_i_robu_izdao", scope = Faktura.class)
    public JAXBElement<String> createFakturaRacunIRobuIzdao(String value) {
        return new JAXBElement<String>(_FakturaRacunIRobuIzdao_QNAME, String.class, Faktura.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Racun_i_robu_primio", scope = Faktura.class)
    public JAXBElement<String> createFakturaRacunIRobuPrimio(String value) {
        return new JAXBElement<String>(_FakturaRacunIRobuPrimio_QNAME, String.class, Faktura.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dodatne_napomene", scope = Faktura.class)
    public JAXBElement<String> createFakturaDodatneNapomene(String value) {
        return new JAXBElement<String>(_FakturaDodatneNapomene_QNAME, String.class, Faktura.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPrevoznik }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Podaci_o_prevozniku", scope = Faktura.class)
    public JAXBElement<TPrevoznik> createFakturaPodaciOPrevozniku(TPrevoznik value) {
        return new JAXBElement<TPrevoznik>(_FakturaPodaciOPrevozniku_QNAME, TPrevoznik.class, Faktura.class, value);
    }

}
