//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 04:04:46 PM CEST 
//


package com.app.model.invoice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idFaktureOtpremnice" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Artikal">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idArtikla" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="sifraArtikla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nazivArtikla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.ftn.uns.ac.rs/faktura}stavkeAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idFaktureOtpremnice",
    "artikal"
})
@XmlRootElement(name = "StavkaFaktureOtpremnice")
public class StavkaFaktureOtpremnice {

    protected long idFaktureOtpremnice;
    @XmlElement(name = "Artikal", required = true)
    protected StavkaFaktureOtpremnice.Artikal artikal;
    @XmlAttribute(name = "idStavkeFakture")
    protected Long idStavkeFakture;
    @XmlAttribute(name = "kolicina")
    protected BigDecimal kolicina;
    @XmlAttribute(name = "rabat")
    protected BigDecimal rabat;
    @XmlAttribute(name = "osnovicaPDV")
    protected BigDecimal osnovicaPDV;
    @XmlAttribute(name = "jedinicnaCenaStavkeFakture")
    protected BigDecimal jedinicnaCenaStavkeFakture;

    /**
     * Gets the value of the idFaktureOtpremnice property.
     * 
     */
    public long getIdFaktureOtpremnice() {
        return idFaktureOtpremnice;
    }

    /**
     * Sets the value of the idFaktureOtpremnice property.
     * 
     */
    public void setIdFaktureOtpremnice(long value) {
        this.idFaktureOtpremnice = value;
    }

    /**
     * Gets the value of the artikal property.
     * 
     * @return
     *     possible object is
     *     {@link StavkaFaktureOtpremnice.Artikal }
     *     
     */
    public StavkaFaktureOtpremnice.Artikal getArtikal() {
        return artikal;
    }

    /**
     * Sets the value of the artikal property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavkaFaktureOtpremnice.Artikal }
     *     
     */
    public void setArtikal(StavkaFaktureOtpremnice.Artikal value) {
        this.artikal = value;
    }

    /**
     * Gets the value of the idStavkeFakture property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdStavkeFakture() {
        return idStavkeFakture;
    }

    /**
     * Sets the value of the idStavkeFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdStavkeFakture(Long value) {
        this.idStavkeFakture = value;
    }

    /**
     * Gets the value of the kolicina property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKolicina() {
        return kolicina;
    }

    /**
     * Sets the value of the kolicina property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKolicina(BigDecimal value) {
        this.kolicina = value;
    }

    /**
     * Gets the value of the rabat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRabat() {
        return rabat;
    }

    /**
     * Sets the value of the rabat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRabat(BigDecimal value) {
        this.rabat = value;
    }

    /**
     * Gets the value of the osnovicaPDV property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOsnovicaPDV() {
        return osnovicaPDV;
    }

    /**
     * Sets the value of the osnovicaPDV property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOsnovicaPDV(BigDecimal value) {
        this.osnovicaPDV = value;
    }

    /**
     * Gets the value of the jedinicnaCenaStavkeFakture property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getJedinicnaCenaStavkeFakture() {
        return jedinicnaCenaStavkeFakture;
    }

    /**
     * Sets the value of the jedinicnaCenaStavkeFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setJedinicnaCenaStavkeFakture(BigDecimal value) {
        this.jedinicnaCenaStavkeFakture = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idArtikla" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="sifraArtikla" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nazivArtikla" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idArtikla",
        "sifraArtikla",
        "nazivArtikla"
    })
    public static class Artikal {

        protected long idArtikla;
        @XmlElement(required = true)
        protected String sifraArtikla;
        @XmlElement(required = true)
        protected String nazivArtikla;

        /**
         * Gets the value of the idArtikla property.
         * 
         */
        public long getIdArtikla() {
            return idArtikla;
        }

        /**
         * Sets the value of the idArtikla property.
         * 
         */
        public void setIdArtikla(long value) {
            this.idArtikla = value;
        }

        /**
         * Gets the value of the sifraArtikla property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSifraArtikla() {
            return sifraArtikla;
        }

        /**
         * Sets the value of the sifraArtikla property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSifraArtikla(String value) {
            this.sifraArtikla = value;
        }

        /**
         * Gets the value of the nazivArtikla property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivArtikla() {
            return nazivArtikla;
        }

        /**
         * Sets the value of the nazivArtikla property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivArtikla(String value) {
            this.nazivArtikla = value;
        }

    }

}
