//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 06:33:45 PM CEST 
//


package com.app.model.invoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPrevoznik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPrevoznik">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naziv_prevoznika" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Broj_kamiona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrevoznik", propOrder = {
    "nazivPrevoznika",
    "brojKamiona"
})
public class TPrevoznik {

    @XmlElement(name = "Naziv_prevoznika", required = true, nillable = true)
    protected String nazivPrevoznika;
    @XmlElement(name = "Broj_kamiona", required = true, nillable = true)
    protected String brojKamiona;

    /**
     * Gets the value of the nazivPrevoznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPrevoznika() {
        return nazivPrevoznika;
    }

    /**
     * Sets the value of the nazivPrevoznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPrevoznika(String value) {
        this.nazivPrevoznika = value;
    }

    /**
     * Gets the value of the brojKamiona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojKamiona() {
        return brojKamiona;
    }

    /**
     * Sets the value of the brojKamiona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojKamiona(String value) {
        this.brojKamiona = value;
    }

}
