//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 06:33:45 PM CEST 
//


package com.app.model.invoice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TStavkaFakture complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStavkaFakture">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sifra_robe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Naziv_robe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Jedinica_mere">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Kolicina">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Jedinicna_cena">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rabat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vrednost_stavke">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Poreska_osnovica">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Stopa_PDV">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="5"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Iznos_PDV">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Prodajna_vrednost">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStavkaFakture", propOrder = {
    "sifraRobe",
    "nazivRobe",
    "jedinicaMere",
    "kolicina",
    "jedinicnaCena",
    "rabat",
    "vrednostStavke",
    "poreskaOsnovica",
    "stopaPDV",
    "iznosPDV",
    "prodajnaVrednost"
})
public class TStavkaFakture {

    @XmlElement(name = "Sifra_robe", required = true)
    protected String sifraRobe;
    @XmlElement(name = "Naziv_robe", required = true)
    protected String nazivRobe;
    @XmlElement(name = "Jedinica_mere", required = true)
    protected String jedinicaMere;
    @XmlElement(name = "Kolicina")
    protected BigDecimal kolicina;
    @XmlElement(name = "Jedinicna_cena", required = true)
    protected BigDecimal jedinicnaCena;
    @XmlElement(name = "Rabat")
    protected BigDecimal rabat;
    @XmlElement(name = "Vrednost_stavke", required = true)
    protected BigDecimal vrednostStavke;
    @XmlElement(name = "Poreska_osnovica", required = true)
    protected BigDecimal poreskaOsnovica;
    @XmlElement(name = "Stopa_PDV", required = true)
    protected BigDecimal stopaPDV;
    @XmlElement(name = "Iznos_PDV", required = true)
    protected BigDecimal iznosPDV;
    @XmlElement(name = "Prodajna_vrednost", required = true)
    protected BigDecimal prodajnaVrednost;

    /**
     * Gets the value of the sifraRobe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraRobe() {
        return sifraRobe;
    }

    /**
     * Sets the value of the sifraRobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraRobe(String value) {
        this.sifraRobe = value;
    }

    /**
     * Gets the value of the nazivRobe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivRobe() {
        return nazivRobe;
    }

    /**
     * Sets the value of the nazivRobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivRobe(String value) {
        this.nazivRobe = value;
    }

    /**
     * Gets the value of the jedinicaMere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJedinicaMere() {
        return jedinicaMere;
    }

    /**
     * Sets the value of the jedinicaMere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJedinicaMere(String value) {
        this.jedinicaMere = value;
    }

    /**
     * Gets the value of the kolicina property.
     * 
     */
    public BigDecimal getKolicina() {
        return kolicina;
    }

    /**
     * Sets the value of the kolicina property.
     * 
     */
    public void setKolicina(BigDecimal value) {
        this.kolicina = value;
    }

    /**
     * Gets the value of the jedinicnaCena property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getJedinicnaCena() {
        return jedinicnaCena;
    }

    /**
     * Sets the value of the jedinicnaCena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setJedinicnaCena(BigDecimal value) {
        this.jedinicnaCena = value;
    }

    /**
     * Gets the value of the rabat property.
     * 
     */
    public BigDecimal getRabat() {
        return rabat;
    }

    /**
     * Sets the value of the rabat property.
     * 
     */
    public void setRabat(BigDecimal value) {
        this.rabat = value;
    }

    /**
     * Gets the value of the vrednostStavke property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostStavke() {
        return vrednostStavke;
    }

    /**
     * Sets the value of the vrednostStavke property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostStavke(BigDecimal value) {
        this.vrednostStavke = value;
    }

    /**
     * Gets the value of the poreskaOsnovica property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPoreskaOsnovica() {
        return poreskaOsnovica;
    }

    /**
     * Sets the value of the poreskaOsnovica property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPoreskaOsnovica(BigDecimal value) {
        this.poreskaOsnovica = value;
    }

    /**
     * Gets the value of the stopaPDV property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStopaPDV() {
        return stopaPDV;
    }

    /**
     * Sets the value of the stopaPDV property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStopaPDV(BigDecimal value) {
        this.stopaPDV = value;
    }

    /**
     * Gets the value of the iznosPDV property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznosPDV() {
        return iznosPDV;
    }

    /**
     * Sets the value of the iznosPDV property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznosPDV(BigDecimal value) {
        this.iznosPDV = value;
    }

    /**
     * Gets the value of the prodajnaVrednost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProdajnaVrednost() {
        return prodajnaVrednost;
    }

    /**
     * Sets the value of the prodajnaVrednost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProdajnaVrednost(BigDecimal value) {
        this.prodajnaVrednost = value;
    }

}
